services:
  - type: web
    name: trading-bot-sa
    env: python
    region: singapore
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.0
      - key: PORT
        value: 10000
